### ISSUE TITLE
math ultimate Node returns SUM instead of selected method for SUBSTRACT values

### ISSUE THREAD

**Issue by VanillaFord** [Supergiovane/node-red-contrib-boolean-logic-ultimate#43]
When selecting the Substract method, the math ultimate node reports using the SUM method instead.
In addition, the returned payload is the SUM of all **absolute** values of the msg.payloads going into the node and not the substract value of all msg.payloads going in.

See screenshot: 
![image](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/48869131/d50bf4b1-9c98-4fe6-89ca-48c9a4f2ac7e)

in that example, the values with three different topics are send into the node, which is configured to use substract method.
From the debug Nodes:
- Value 1:  -1244.50
- Value 2: +1133.46
- Value 3: -2417.00
Results: 
- from Node (reporting using SUM): 4794.96 = abs(-1244.50) + abs(1133.46) + abs(-2417.00) -> wrong
- from math calculator: (-1244.50) - (+1133.46) - (-2417.00) = +39.04

**Comment by Supergiovane** [comment]
Hi
I’ll take a look tomorrow morning…

**Comment by Supergiovane** [comment]
Hi

`from math calculator: (-1244.50) - (+1133.46) - (-2417.00) = +39.04`

You're assuming (right assumption), that the first topic the node receives is -1244.50. Currently, the "subtract" function threat the numbers like this instead: - (-1244.50) - (+1133.46) - (-2417.00), so the -1244.50 becomes +1244.50.

I could assume that the first topic received, is the number to start subtracting for. 
Your're right. I'll publish a fixed version asap.

**Comment by Supergiovane** [comment]
Hi
Should be fixed. V. 1.1.4 is out.

**Comment by VanillaFord** [comment]
Hi @Supergiovane 

thanks for your prompt response and support.
Unfortunately this bug is not fixed for me:
![image](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/48869131/1847010f-cd3e-49a6-8e2d-372381044b60)

The "correct" value from a calculator is +18, here.

> I could assume that the first topic received, is the number to start subtracting for.

No, I was not assuming that.
The order of appearance - as well as the number of measures/topics - is not assumed for....as NR is event based, any topic could arrive at any time. However, in my example/flow the number is fixed (3).
The node should (re-)calc with every incoming msg using any number of available measures/topic at that time.
If helpfull, maybe make the number of measures (optionally) fixed so if not all expected/configured topics did arrive at least once, the node would not output a wrong value?

**Comment by VanillaFord** [comment]
...here is another example:
![image](https://github.com/Supergiovane/node-red-contrib-boolean-logic-ultimate/assets/48869131/50fd4e88-b281-4c8a-bc69-c0ed1ff8e419)
...the correct/expected value would be: 2062.4 = (-17.1) - (0) - (-2079.5)

**Comment by Supergiovane** [comment]
Hi
i'll take a look at the average.
About the "subtract", i can put another property in the config window. Here you can write the topic name that should be taken into account, as the first number. You can set it to "GRID_Power", for example.
Could this do the trick?

**Comment by Supergiovane** [comment]
In the meantime, i've fixed the "average".

**Comment by Supergiovane** [comment]
Please try the 1.1.6. You must now set a msg.topic to start subtracting from.

**Comment by VanillaFord** [comment]
> Please try the 1.1.6. You must now set a msg.topic to start subtracting from.

...this version doesn't show up in the pallette manage, yet

**Comment by Supergiovane** [comment]
> > Could this do the trick?
> 
> Yes I think it could, thank you.
> 

> 
> Perfect, please keep in mind, that the payload is also affected.
> 

The payload is not sent until the **main topic** hasn't been received.

**Comment by VanillaFord** [comment]
> Should show up in some minutes... npmjs takes a little log to update.

Yep, now it is showing (v1.1.7) ...and a first test confirms, that it is working now.
Thank you very much for your fast response and support!!

**Comment by Supergiovane** [comment]
You’re wellcome!!
